### PR TITLE
Assertions

### PR DESCRIPTION
**Pull request by niels-qup**
Draft PR for testing. what do you guys think ? Check README.md for signature.

### CODE REVIEW

**Review by pcittadini — COMMENTED** [review]
looks promising to me, I will test this locally as well.

**Review by pcittadini — APPROVED** [review]
good to go for me. I'd like to have this in master, minor bugs/improvements can be PR'd later :)

**Review by pcittadini — CHANGES_REQUESTED** [review]
maybe we want to have green tests first

**Comment by niels-qup** [comment]
Tests are passing, retarded docker login is failing though.

**Review by pcittadini — APPROVED** [review]
nice

**Pull request merged**
