### PR TITLE
Feature/secretsmanager

### PR DESCRIPTION
**Pull request by niels-qup**

### CODE REVIEW

**Comment by pcittadini** [comment]
How we are suppose to retrieve plain secrets as not all secrets are supposed to be json/struct?
Does the GetSecretsValue needs to be implemented client wise?

**Comment by niels-qup** [comment]
The idea behind this function is to mimic the behavior of the `envvar.ToStruct` method. So in the lambda main function i usually map all my envvars directly to an environmental struct this is a function that can do the same with secretsmanager.
There are some more adjustments I have to make, so I'll convert it back to draft, as requested I will also add some boiler plating for easily retrieving and storing secrets.

**Comment by pcittadini** [comment]
> The idea behind this function is to mimic the behavior of the `envvar.ToStruct` method. So in the lambda main function i usually map all my envvars directly to an environmental struct this is a function that can do the same with secretsmanager. There are some more adjustments I have to make, so I'll convert it back to draft, as requested I will also add some boiler plating for easily retrieving and storing secrets.

Yes, this part I like. I'd just probably leave, the happy flow, key/value secret retrieval (think jdbc strings and a lot of legacy secrets). But so far, so good, like the idea.

**Review by pcittadini — APPROVED** [review]
Loook soo good

**Comment by niels-qup** [comment]
Just added a backwards compatible function so we don't have to bump major version.

**Pull request merged**
